import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
import NavBar2 from '../components/NavBar2';
import Banner from '../components/Banner'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jani Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Component-2.ico" />
      </Head>
      <NavBar />
      <NavBar2 />
      <Banner title={`Top deals`} />
      <Banner title={`Explore popular categories`} />
      <Banner title={`Popular Brands`} />
      {/* body of the project to be here */}
      <Footer />
    </div>
  )
}
